# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genq < Formula
  desc ""
  homepage ""
  version "0.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jankuss/genq/releases/download/0.6.0/genq_Darwin_x86_64.tar.gz"
      sha256 "9d55d26d4b2706530fe0e2c35ddffddfb48e241d946a326613b3937f020dcad7"

      def install
        bin.install "genq"
      end
    end
    on_arm do
      url "https://github.com/jankuss/genq/releases/download/0.6.0/genq_Darwin_arm64.tar.gz"
      sha256 "095d50d316a1f31fbc83516159e8b6d93294d9dfbb11b70c2e44a3f0c75125f9"

      def install
        bin.install "genq"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jankuss/genq/releases/download/0.6.0/genq_Linux_x86_64.tar.gz"
        sha256 "3401a494affe189e24d9c48177fa4e63a0d41053ec7c583c4c83ef362d2c0e6d"

        def install
          bin.install "genq"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jankuss/genq/releases/download/0.6.0/genq_Linux_arm64.tar.gz"
        sha256 "59f4bc892118cbea43d8ce3f2e5ef7f925396521f69390956b4892e08d940970"

        def install
          bin.install "genq"
        end
      end
    end
  end
end
