# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Genq < Formula
  desc ""
  homepage ""
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jankuss/genq/releases/download/0.2.1/genq_Darwin_x86_64.tar.gz"
      sha256 "42f788fd77adaae7ae0a11d8d36757e7307db6514a61aada284fe158c1347238"

      def install
        bin.install "genq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jankuss/genq/releases/download/0.2.1/genq_Darwin_arm64.tar.gz"
      sha256 "324f8b314c5007bcbffdc60de1d84f91f0924b42917e3ea79b3d25020ee47f52"

      def install
        bin.install "genq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jankuss/genq/releases/download/0.2.1/genq_Linux_x86_64.tar.gz"
      sha256 "d16ea09fbffde6b3276bde2fc08edc8ee55e002b9fd86153b09bcddc325a582f"

      def install
        bin.install "genq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jankuss/genq/releases/download/0.2.1/genq_Linux_arm64.tar.gz"
      sha256 "31da7588d2ce2050d0d5afcd2c48c5a7934275cd66557a5ee357e702ec6a3f67"

      def install
        bin.install "genq"
      end
    end
  end
end
